### ISSUE TITLE
Paper dashboard build for production

### ISSUE THREAD

**Issue by darasat** [creativetimofficial/paper-dashboard-react#1]
Good day 

 I am deploying the paper-dashboard-react  but I could not build for production with the command (npm run build), 
executing the command "npm run build" uncaught syntax error unexepected token

what could I do ?

so many thanks

**Comment by einazare** [comment]
Hello there @darasat ,

Thank you for your interest in working with our products.
Here is my output when running npm run build:
<img width="875" alt="screen shot 2018-11-01 at 7 17 51 pm" src="https://user-images.githubusercontent.com/26245512/47867776-2fa2b900-de0b-11e8-9c9f-8102072ebeb8.png">
As you can see everything works perfectly.

I am guessing you have done some changes to our product and that is why you have this issue?

Also, why did you not complete our ISSUES_TEMPLATE ?
```
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.
```

Best,
Manu

**Comment by darasat** [comment]
thank you EINazare  

this solves my doubts


The issue is solved
