### ISSUE TITLE
[Bug] problem with file upload inputs 

### ISSUE THREAD

**Issue by rm116** [creativetimofficial/paper-dashboard-react#12]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/
### Operating System
Windows 10
### Device
PC 
### Browser & Version
Google Chrome
### Steps to reproduce
1 . add a code to a simple file upload 
                        <h6><Label for="exampleFile">Upload files</Label></h6>
                        
                          <Input id="exampleFile" type="file">aaaaaaa</Input>
                      
### What is expected?
an upload input is created with upload possibility.
### What is actually happening?
The input is not showing , even with a simple <input> , But when I hover the mouse I see the text "upload" and I can click. But no visual result.

---
### Additional comments
Thanks

**Comment by einazare** [comment]
Hello again, @rm116 ,

Please go inside `src/assets/scss/paper-dashboard/_inputs.scss` and delete the following bits of code:
```
// Input files - hide actual input - requires specific markup in the sample.
.form-group input[type=file] {
  opacity: 0;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 100;
}
```

Best,
Manu
