### ISSUE TITLE
Sidebar is scrollable on x-axis

### ISSUE THREAD

**Issue by algoroad** [creativetimofficial/paper-dashboard-react#13]
**Version**
1.1.0

**Reproduction link**
https://demos.creative-tim.com/paper-dashboard-react/#/admin/dashboard

**Operating System**
OSX

**Device**
Macbook Pro

**Browser & Version**
Chrome 81

**Steps to reproduce**
Run paper dashboard react

**What is expected?**
I would like the sidebar to not have scrollbar visible for the x-axis

**What is actually happening?**
Sidebar is able to scroll on x-axis and scrollbar is visible at the bottom
![Screen Shot 2020-04-27 at 11 45 28](https://user-images.githubusercontent.com/58657636/80363795-a55ed800-887c-11ea-8e83-833430b0a3f4.png)

**Comment by einazare** [comment]
Hello there, @ddharvey ,

Thank you for your interest in working with our products.
Please add the following CSS code:
```
@media screen and (min-width: 992px) {
     .sidebar .sidebar-wrapper li.active>[data-toggle=collapse]+div .nav li:before, 
     .sidebar .sidebar-wrapper li.active>a:not([data-toggle=collapse]):before {
           right: -14px;
     }
     .sidebar .sidebar-wrapper li.active>[data-toggle=collapse]+div .nav li:after, 
     .sidebar .sidebar-wrapper li.active>a:not([data-toggle=collapse]):after {
           right: -15px;
     }
}
```

Best,
Manu

**Comment by algoroad** [comment]
Thanks for the reply. 

Unfortunately, I have tried adding the css to 'paper-dashboard.css' but it has not worked.

**Comment by einazare** [comment]
Hello again, @ddharvey ,

Please create a new css file with the above code, and import that css file inside your index.js file after our styles.

Best,
Manu

**Comment by ddharvey** [comment]
It worked!

Thanks @EINazare.

**Comment by einazare** [comment]
I'll leave the issue opened, so that if somebody else has this problem, to see it here.
