### ISSUE TITLE
Remove y-axis visible scrollbar on sidebar

### ISSUE THREAD

**Issue by algoroad** [creativetimofficial/paper-dashboard-react#14]
**Version**
1.1.0

**Reproduction link**
https://demos.creative-tim.com/paper-dashboard-react/#/admin/dashboard

**Operating System**
OSX

**Device**
Macbook Pro

**Browser & Version**
Chrome 81

**Steps to reproduce**
Run paper dashboard react

**What is expected?**
I would like the sidebar to not have scrollbar visible for the y-axis. But I would still like to be able to scroll.

**What is actually happening?**
Scrollbar is visible on y-axis when browser window is less than a certain height.

![Screen Shot 2020-05-03 at 13 49 07](https://user-images.githubusercontent.com/58657636/80914665-eeaf9b80-8d44-11ea-8f57-90d5dcafd8b8.png)
![Screen Shot 2020-05-03 at 13 49 16](https://user-images.githubusercontent.com/58657636/80914668-f1aa8c00-8d44-11ea-81ad-6c64fa17046e.png)

**Comment by einazare** [comment]
Hello there, @ddharvey ,

That is browser default behavior and cannot be changed.

Best,
Manu
