### ISSUE TITLE
[Bug] Not compatible with latest version of react

### ISSUE THREAD

**Issue by skushnir123** [creativetimofficial/paper-dashboard-react#15]
### Version
Latest Version
### Reproduction link
https://github.com/creativetimofficial/material-dashboard-react
### Operating System
Linux
### Device
Mac
### Browser & Version
Chrome lastest version
### Steps to reproduce
Install Paper Dashboard React, change react to latest version and run npm install.
### What is expected?
load the page
### What is actually happening?
error with not being able to load icons

---

**Comment by einazare** [comment]
Hello there, @skushnir123 ,

We'll make an update to this product in the following months.

Best,
Manu
