### ISSUE TITLE
[Bug] Deployment Issue

### ISSUE THREAD

**Issue by Sudhakar555** [creativetimofficial/paper-dashboard-react#18]
### Version
Yes
### Reproduction link
https://github.com/Sudhakar555/Covid-Dashboard
### Operating System
Windows 10 
### Device
Lenovo Desktop
### Browser & Version
Chrome  85.0.4183.121
### Steps to reproduce
1. Build File for deployment.
2. Try to deploy in Netlify and Github.
3.Only one time its loading.after refreshing it went.
### What is expected?
Deployment in netlify and github pages should be working fine.
### What is actually happening?
The page is loading without images and 404 after a refresh.

---
### Additional comments
Kindly help me fix this ASAP.

**Comment by einazare** [comment]
Hello there, @Sudhakar555 ,

Unfortunately, this is not a bug from our product, but from react-scripts and/or react-router.
You can solve this issue by changing the BrowserRouter to a HashRouter inside index.js.

Best,
Manu
