### ISSUE TITLE
[Feature Request] Netlify/Github deploy Failure

### ISSUE THREAD

**Issue by Sudhakar555** [creativetimofficial/paper-dashboard-react#19]
### What is your enhancement?
I am currently using free version of paper dashboard for my dashboard. i did some changes from the template and tried to deploy it on netlify/github pages. Its successfully building but after deploy images are not loading and when i try to refresh it becomes 404 not found. 
i have tried other applications for deploying and its correctly working. only paper dashboard is facing this issue. its not a bug report. it will be very useful if you help me to get the solution.

**Comment by einazare** [comment]
duplicate of #18
