### ISSUE TITLE
Extra white space on demo site and cloned project

### ISSUE THREAD

**Issue by urielp** [creativetimofficial/paper-dashboard-react#2]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
each page should be scroll-able only if needed.
no extra white space  
# Current Behavior
there is an extra white space (after footer) which we can scroll to causing color differences 
(tried on edge,chrome)

**Comment by einazare** [comment]
Hello there @urielp ,

This is because we've forgotten to add the PerfectScrollBar's styles.
Just go inside the Admin layout and add the following import:
```
import "perfect-scrollbar/css/perfect-scrollbar.css";
```
It should work like a charm.

Best,
Manu

**Comment by urielp** [comment]
Thanks a lot for the quick response  😊

 

I saw that missing import but was not sure if it was by design or just by mistake.

Works now 

 

Thanks  

 

 

Uriel

 

 

מאת: Nazare Emanuel-Ioan <notifications@github.com>
כתובת להשבה: creativetimofficial/paper-dashboard-react <reply@reply.github.com>
תאריך: יום שישי, 28 בדצמבר 2018 בשעה 12:20
אל: creativetimofficial/paper-dashboard-react <paper-dashboard-react@noreply.github.com>
עותק: Uriel Parienti <urielprb@gmail.com>, Mention <mention@noreply.github.com>
נושא: Re: [creativetimofficial/paper-dashboard-react] Extra white space on demo site and cloned project (#2)

 

Hello there @urielp ,

This is because we've forgotten to add the PerfectScrollBar's styles.
Just go inside the Admin layout and add the following import:
import "perfect-scrollbar/css/perfect-scrollbar.css";
It should work like a charm.

Best,
Manu

**Comment by urielp** [comment]
thanks again,
sorry for the delay in closing this issue.
i was sure that i closed it right after you provided the fix .
