### ISSUE TITLE
Help needed - Change Sidebar

### ISSUE THREAD

**Issue by peter-medaf** [creativetimofficial/paper-dashboard-react#22]
### What is your enhancement?
is there is a way that i can make the sidebar hidden even in the large screens, and the icon to appear
that's will make the dashboard view even better and better
and it's requested also by clients

**Comment by einazare** [comment]
Hello there, @peter-medaf ,

Unfortunately, there is no way of achieving that. 
We will leave your issue opened up until our next update, maybe someone from our community will be able to help you.

Best,
Manu

**Comment by peter-medaf** [comment]
Thanks a lot
