### ISSUE TITLE
[Bug] React development server live-reload breaks navigation

### ISSUE THREAD

**Issue by AuroraLS3** [creativetimofficial/paper-dashboard-react#25]
### Version
1.3.0
### Reproduction link
https://github.com/creativetimofficial/paper-dashboard-react
### Operating System
Windows 10
### Device
PC
### Browser & Version
Firefox 96.0.1 (64-bit)
### Steps to reproduce
1. Clone the template - git clone https://github.com/creativetimofficial/paper-dashboard-react.git
2. Run npm install
3. Run npm start
4. Wait until the template opens in the browser
5. Make a change to one of the React components in the template and save the file to trigger a live reload
6. Wait for live-reload to occur
7. Try to scroll on the page or click one of the items in the sidebar
### What is expected?
The website should continue to function after a live-reload.
### What is actually happening?
Scrolling the website and any react-router links stops working, requiring a full refresh of the browser window - breaking workflow.

---

**Comment by sajadevo** [comment]
**Hi @AuroraLS3**

Thanks for using our product, I've just updated the product you can check it now.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
