### ISSUE TITLE
[Feature Request/Question] How to change de SideBar on the flow?

### ISSUE THREAD

**Issue by JoaoGabrielM** [creativetimofficial/paper-dashboard-react#5]
Hi!

I want to change the links in the side bar on the flow.

I have a link that can't be accessible if the user is not logged. I've treated that on the routers file, but I don't know how to get this file again and change the sidebar.

Thanks!

**Comment by einazare** [comment]
Hello there, @JoaoGabrielM ,

Thank you for your interest in working with our product.
I do not quite follow your question.
Do you mean to ask what changes you have to do inside the sidebar?
Also, could you please provide this code: `I've treated that on the routers file` ?

Best,
Manu

**Comment by JoaoGabrielM** [comment]
Hi, Thanks for answering me.

On the routers file I have

`
import Login from "components/Login";
import Logout from "components/Logout";

const invisible = !localStorage.getItem('auth-token-access');

var routes = [
  { ... },
  {
    invisible: invisible,
    pro: true,
    path: "/logout",
    name: "Logout",
    icon: "nc-icon nc-spaceship",
    component: Logout,
    layout: ""
  },
  {
    invisible: !invisible,
    pro: true,
    path: "/login",
    name: "Login",
    icon: "nc-icon nc-spaceship",
    component: Login,
    layout: ""
  }
];
export default routes;
`

I want that when a user do the loggin, that the sidebar update to show the right button.

Before use this template, I was forcing the update of the main component to re-render the sidebar, but now this does not work.

Thanks again!

**Comment by einazare** [comment]
Hello there, @JoaoGabrielM ,

I still am not sure that I do not understand your question.
So, I believe what you are looking for is to go inside `src/components/Sidebar/Sidebar.jsx`, and after this line:
```
{this.props.routes.map((prop, key) => {
```
you can add the following code:
```
if(prop.invisible){
    return null;
}
```
But I believe your routes code should look like:
```
import Login from "components/Login";
import Logout from "components/Logout";

const invisible = !localStorage.getItem('auth-token-access');

var routes = [
{ ... },
{
invisible: invisible,
pro: true,
path: "/logout",
name: "Logout",
icon: "nc-icon nc-spaceship",
component: Logout,
layout: ""
},
{
invisible: invisible,
pro: true,
path: "/login",
name: "Login",
icon: "nc-icon nc-spaceship",
component: Login,
layout: ""
}
];
export default routes;
```

So, no `invisible: !invisible,`, just `invisible: invisible,` everywhere.

Hope this helps.

Best,
Manu

**Comment by JoaoGabrielM** [comment]
I will try to clarify. Sorry for my English!

I have the Sidebar that show the button to do the login.

When the user does the login, I want to change the login button to the logout button.

When I used the full route in the `index.js` file, i could do this change forcing the update of the main component, because i had written the links handmaid. But now, I have the links in a file, and I don't know how to say to Sidebar to re-read this file to update the visualization.

Translating...

Show the login button -> user does the login -> show the logout button instead the login button.

Again, sorry for my English and thanks for the attention!

**Comment by einazare** [comment]
Hello again, @JoaoGabrielM ,

So, I was right with my last comment.
Just follow the steps there, and you will achieve your effect.

Best,
Manu
