### ISSUE TITLE
paper-dashboard-react is not working with react-scripts@3.1.1

### ISSUE THREAD

**Issue by rudza** [creativetimofficial/paper-dashboard-react#6]
Tried upgrading react-script to v3.1.1 but getting this error: 

```
Failed to compile.

./src/assets/scss/paper-dashboard.scss?v=1.1.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/paper-dashboard.scss?v=1.1.0)
Module not found: Can't resolve './fonts/nucleo-icons.eot' in '/home/rudolfs/workspace/Grafomap/dashboard.grafomap.com/src/assets/scss'
```

When I try to fix this error with `"start": "NODE_PATH=./src react-scripts start",` as mentioned in the docs here https://demos.creative-tim.com/paper-dashboard-react/#/documentation/quick-start, I get this warning 
```
Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.

Starting the development server...
```
followed by the same Module not found error

Also, I have configured jsconfig.json:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}
```

And still no luck. Please help. :)

**Comment by einazare** [comment]
Hello there, @rudza 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/paper-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
This being said, to respond to your question, please wait for our update - we do not offer support for changes in our dependencies. On each new version that we release we update our products dependencies to the latest.

All the best,
Manu
Developer @ [Creative-Tim.com](http://creative-tim.com/)

**Comment by syrakozz** [comment]
hi any solution for this @EINazare

**Comment by einazare** [comment]
Hello, @syrakozz ,

Please read my last comment.

Thank you,
Manu
