### ISSUE TITLE
Missing CustomButton

### ISSUE THREAD

**Issue by yasir2000** [creativetimofficial/paper-dashboard-react#7]
At line 25:
import Button from "components/CustomButton/CustomButton.jsx";
the whole CustomButton folder does not exist in this branch

**Comment by einazare** [comment]
Hello there, @yasir2000 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/paper-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Manu
Developer @ [Creative-Tim.com](http://creative-tim.com/)
