### ISSUE TITLE
[Bug] Module not found: Can't resolve './fonts/nucleo-icons.eot'

### ISSUE THREAD

**Issue by mkaimakamian** [creativetimofficial/paper-dashboard-react#8]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/paper-dashboard-react/#/documentation/quick-start
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Doesn't build
### Steps to reproduce
I just follow the instruction described here: https://demos.creative-tim.com/paper-dashboard-react/#/documentation/quick-start

However, after executing npm start the following error appeared:

./src/assets/scss/paper-dashboard.scss?v=1.1.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/paper-dashboard.scss?v=1.1.0)
Module not found: Can't resolve './fonts/nucleo-icons.eot' in 'C:\Users\mcarrau\Documents\CloudPosAdminFrontend\src\assets\scss'

So I did this...
npm install --g cross-env

And then...
change "start": "react-scripts start" to "start": "NODE_PATH=./src react-scripts start" in package.json... same error.

But the error following error was shown:

> paper-dashboard-react@1.1.0 start C:\Users\mcarrau\Documents\CloudPosAdminFrontend
> NODE_PATH=./src react-scripts start

"NODE_PATH" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paper-dashboard-react@1.1.0 start: `NODE_PATH=./src react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the paper-dashboard-react@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

So I revert the changes and tried in the console:
set NODE_PATH="./src"
npm start

Several seconds later this warning appeared:
Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.

To finally get the samne first message.
### What is expected?
I was hopping to get this working
### What is actually happening?
Can't compile.

---

**Comment by einazare** [comment]
Hello there, @mkaimakamian ,

Please create file named jsconfig.json and add the following code inside it:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}

```
Everything will work fine after that.

Best,
Manu

**Comment by mkaimakamian** [comment]
Thanks for you fast reply 😄 !

This files already exist (as far as I know, cross-env requires it to handle compatibility among different OS) so I guess the problem has its origing in other place.
I repeated the operation described in the doc several times without any success; I also replaced the content of my jsconfig.json with yours (was the same, but I had nothing to lose) and the situation remain the same.

Digging in Internet doesn't revealed any helpful information, most websites talks about jsconfig.json or suggest set node_path as I did.

I'm pretty lost ... is there any more technical data that I can provide in order to find a solution?

I'm using Node v12.14.1 and Windows 10 as I said.

Thanks in davance for any help!

![imagen](https://user-images.githubusercontent.com/23729868/72892519-796c0d80-3cf5-11ea-9827-2dcde2bebbda.png)

**Comment by einazare** [comment]
Hello again, @mkaimakamian ,

What if you run `npm i -E node-sass@4.13.0`?
I remember that was an issue on some other products, for some reason the new nodejs version does not work well with older node-sass versions.

Let me know if that helped.

Best,
Manu

**Comment by mkaimakamian** [comment]
Manu, thanks for your help.
Unfortunately I got same error.

Any other suggestion? 😢 

![imagen](https://user-images.githubusercontent.com/23729868/72916527-f365bc00-3d20-11ea-897f-8f3cd278278a.png)

**Comment by einazare** [comment]
Hello again, @mkaimakamian ,

So by the error, I understand that node-sass does not see the fonts folder.
It is very strange, as on my Machines (both MacOS and Windows 10), it works perfectly.
I think the solution is to move the `src/assets/fonts` inside the `src/assets/scss` folder.

Let me know if that worked.

Best,
Manu

**Comment by mfahadtahir** [comment]
@EINazare i tried moving too, still the same error

once it worked yesterday and today but as i made changes in code and than tried npm start again it gave the same error

**Comment by mfahadtahir** [comment]
Done
Go in scss/paper-dashboard/react/costum/_nucleo-outline.scss
and update the url(../font/nucleo-outline.scss) to url(../../../../font/nucleo-outline.scss)

![Screenshot_20200126_165828](https://user-images.githubusercontent.com/40818615/73134850-47440e00-405d-11ea-93b4-a96c77039ffc.png)

**Comment by kriscodes2** [comment]
![urlResolveIssue](https://user-images.githubusercontent.com/46583664/77247643-3ee8f900-6bf0-11ea-8bd5-3d5a6c826483.PNG)

I am having the same issue. For me it started after a git clone. I thought it may have to do with CR Line endings so I tried the remove cr option and tried all above solutions to no avail. I even re-installed the base template separately and it is not working either....

The only other variable is css mapping. I also added my own nucleo icons with props right before this happened. Please help

**Comment by einazare** [comment]
> Hello again, @mkaimakamian ,
> 
> So by the error, I understand that node-sass does not see the fonts folder.
> It is very strange, as on my Machines (both MacOS and Windows 10), it works perfectly.
> I think the solution is to move the `src/assets/fonts` inside the `src/assets/scss` folder.
> 
> Let me know if that worked.
> 
> Best,
> Manu

Hello there, @grownanny ,

Please refer to this reply.

Best,
Manu

**Comment by kriscodes2** [comment]
I did a bit more research and found that the source of the issue was
upgrading packages as found in previous posts. I did use that fix for
another product of your (dashboard-dark-react) and that worked perfectly.
My use case is involves using aws-amplify which tries to upgrade node-sass.
I downgraded the packages and the product is working fine now. I really
truly appreciate your reply and stand behind your product. In light of the
recent virus I purchased the paper dashboard to create a place for people
suffering from the virus to share their stories. Your product has enabled
me to work much quicker than from scratch. In the license area I would like
to extend a special thanks to the creative Tim team. Thanks again for your
hard work.

**Comment by einazare** [comment]
Hello again, @grownanny ,

Glad everything works fine now.
Would you be interested in sharing with us your tool/website, so that we may add it in one of our newsletters/social media?
We are interested in showcasing our users the best projects, especially projects made with our products, in this virus context outbreak.

Best,
Manu

**Comment by kriscodes2** [comment]
Sure I'm learning as I go and it is not complete but it is up and running at www.BraveCOVID.com.

I am racing to get a MVP using your product, facebook style blogs, and a media transcoder to convert user videos. Also, I would love any input as it is a work in progress. I will update when complete. Thanks again.

**Comment by malikimran21** [comment]
i had the same issue, i have resolved this by navigating to the folder as @fahadtahir226  suggested 
"../../fonts/nucleo-outline.eot". just put .. and find fonts/nucleo-outline.eot then update paths for all
