### ISSUE TITLE
[Bug] Inside page navigation problem

### ISSUE THREAD

**Issue by rm116** [creativetimofficial/paper-dashboard-react#9]
### Version
v1.1.0
### Reproduction link
https://codepen.io/
### Operating System
Windows 10
### Device
PC 
### Browser & Version
Google Chrome
### Steps to reproduce
If I open the page without a mouse , I will be blocked because the inside navigator (up and down) in the page is not showing 
### What is expected?
the navigator (to move from start to bottom of the page) is showing on loading.

[Link to image
](https://ibb.co/XSFbDr7)
### What is actually happening?
I must use mouse or change zoom to show. I can be blocked in the head of the page

---

**Comment by einazare** [comment]
Hello there, @rm116 ,

Thank you for your interest in working with our products.
Please go inside `src/layouts/Admin.jsx` and `src/components/Sidebar/Sidebar.jsx` and delete the following bits of codes:
```
  componentDidMount() {
    if (navigator.platform.indexOf("Win") > -1) {
      ps = new PerfectScrollbar(this.mainPanel.current);
      document.body.classList.toggle("perfect-scrollbar-on");
    }
  }
  componentWillUnmount() {
    if (navigator.platform.indexOf("Win") > -1) {
      ps.destroy();
      document.body.classList.toggle("perfect-scrollbar-on");
    }
  }
```
```
  componentDidMount() {
    if (navigator.platform.indexOf("Win") > -1) {
      ps = new PerfectScrollbar(this.sidebar.current, {
        suppressScrollX: true,
        suppressScrollY: false
      });
    }
  }
  componentWillUnmount() {
    if (navigator.platform.indexOf("Win") > -1) {
      ps.destroy();
    }
  }
```

Best,
Manu
